# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# hide errors
show_stacktrace: 0

# disable server tokens in production environments
no_server_tokens: 1

# config.yml
plugins:
  Database:
    driver: 'Pg'
    dsn: 'dbi:Pg:dbname=defaultdb;host=$ENV{DB_URL};port=15560'
    user: $ENV{'DB_USER'}
    pass: $ENV{'DB_PASSWORD'}
    
session: "Simple"
session_cookie_key: "dancer2.session"
session_expires: 8
